# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Event Advertising' do
  # Comment the next line if you don't want to use dynamic frameworks
  #  add the Firebase pod for Google Analytics
  pod 'Firebase'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Core'
  pod 'Firebase/Analytics'
  pod 'Firebase/Firestore'
  # add pods for any other desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  use_frameworks!

  # Pods for Event Advertising

  target 'Event AdvertisingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Event AdvertisingUITests' do
    # Pods for testing
  end

end
